---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Autofac:
        patterns:
          - "Autofac"
          - "Autofac.*"
      DnsClient:
        patterns:
          - "DnsClient"
      FluentValidation:
        patterns:
          - "FluentValidation"
          - "FluentValidation.*"
      GeoJSON:
        patterns:
          - "GeoJSON.Text"
      MediatR:
        patterns:
          - "MediatR"
          - "MediatR.*"
      Microsoft:
        patterns:
          - "Microsoft.*"
        exclude-patterns:
          - "Microsoft.NET.Test.Sdk"
      MudBlazor:
        patterns:
          - "MudBlazor"
      Npgsql:
        patterns:
          - "Npgsql.EntityFrameworkCore.PostgreSQL"
          - "Npgsql.EntityFrameworkCore.PostgreSQL.Design"
      NSwag:
        patterns:
          - "NSwag.ApiDescription.Client"
      Serilog:
        patterns:
          - "Serilog"
          - "Serilog.*"
      Swashbuckle:
        patterns:
          - "Swashbuckle.AspNetCore"
      Testing:
        patterns:
          - "FluentAssertions"
          - "Microsoft.NET.Test.Sdk"
          - "xunit"
          - "xunit.*"
          - "coverlet.collector"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"