---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
        exclude-patterns:
          - "Microsoft.NET.Test.Sdk"
      mediatr:
        patterns:
          - "MediatR"
          - "MediatR.*"
      postgresql:
        patterns:
          - "Npgsql.EntityFrameworkCore.PostgreSQL"
          - "Npgsql.EntityFrameworkCore.PostgreSQL.*"
      autofac:
        patterns:
          - "Autofac"
          - "Autofac.*"
      serilog:
        patterns:
          - "Serilog"
          - "Serilog.*"
      testing:
        patterns:
          - "FluentAssertions"
          - "Microsoft.NET.Test.Sdk"
          - "xunit"
          - "xunit.*"
          - "coverlet.collector"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"