name: .NET Build & Test

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    name: .NET Build & Test
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Tools
        run: |
          cd Backend/Bones.Api
          dotnet tool restore
          cd ../..
          cd Frontend/Bones.Api.Client
          dotnet tool restore
          cd ../..

      - name: Build
        run: |
          dotnet build --no-incremental
          git diff --quiet || exit 1

      - name: Test
        run: dotnet test --no-build

      - name: Publish Client and Server
        run: |
          dotnet publish Backend/Bones.Api/Bones.Api.csproj --configuration Release --runtime linux-x64 --self-contained true --property PublishDir=~/publish-server
          dotnet publish Frontend/Bones.WebUI/Bones.WebUI.csproj --configuration Release --property PublishDir=~/publish-client

      - name: Upload Server Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-linux-x64
          path: ~/publish-server

      - name: Upload Client Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: ~/publish-client