name: .NET Build & Test

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    name: .NET Build & Test
    runs-on: ubuntu-latest
    env:
      Database__UseInMemoryDb: true
      GITHUB_ACTION_BUILD: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Tools
        run: |
          cd Bones.Api
          dotnet tool restore
          cd ..
          cd Bones.WebUI
          dotnet tool restore
          cd ..

      - name: Build
        run: dotnet build --no-incremental

      - name: Test
        run: dotnet test --no-build
      